[project]
name = "hmpps-terraform-discovery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gitpython==3.1.45",
    "hmpps-python-lib",
    "tfparse==0.6.18",
]

[tool.uv.sources]
hmpps-python-lib = { url = "https://github.com/ministryofjustice/hmpps-python-lib/releases/download/v0.1.8/hmpps_python_lib-0.1.8-py3-none-any.whl" }
